### ISSUE TITLE
你还是搞技术吧

### ISSUE THREAD

**Issue by maplesugarr** [liuyubobobo/my-blog#2]
你是政治白痴，还是搞技术吧，老师。

**Comment by liuyubobobo** [comment]
1 我一直搞技术；2 有不同观点可以交流，直接说别人白痴真的没水平；3 当然，真要觉得我的一些观点白痴到无法沟通的地步，请千万别再看我的文章了，不要委屈自己，没必要；4 感谢反馈，我会继续努力的，你也加油：）

**Comment by conanjunn** [comment]
力挺bobo老师~

**Comment by liuyubobobo** [comment]
谢谢你：）加油！：）

**Comment by liuyubobobo** [comment]
> 力挺bobo老师~

谢谢你！你也加油！：）
